apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "shipping"
  description: "shipping api"
spec:
  type: openapi
  lifecycle: production
  owner:  "platform-dx"
  definition:
    $text: https://github.com/platform-dx/shipping230209/blob/main/open-api.yaml